server:
  port: 8081

spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: kafka:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false

  mongodb:
    uri: "mongodb://admin:admin123@mongodb:27017/orderdb?authSource=admin"

  data:
    mongodb:
      auto-index-creation: false

springdoc:
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: "*"